CREATE TABLE IF NOT EXISTS "ages"."geodata_info" (
	"geopackage" TEXT,
	"gpkg_uuid" UUID NOT NULL,
	"leverans" UUID,
	"geom" BLOB(point,3006),
	"manuell_rektifiering" BOOLEAN DEFAULT FALSE,
	PRIMARY KEY("gpkg_uuid")
);




CREATE TABLE IF NOT EXISTS "ages"."rapportLank" (
	"gpkg_uuid" UUID,
	"rapportejkmr" TEXT,
	PRIMARY KEY("gpkg_uuid", "ages"."rapportejkmr")
);




CREATE TABLE IF NOT EXISTS "ages"."rel2raa_arkiv" (
	"gpkg_uuid" UUID,
	"raa_arkiv_uuid" UUID,
	PRIMARY KEY("gpkg_uuid", "raa_arkiv_uuid")
);




CREATE TABLE IF NOT EXISTS "ages"."rel2uppdrag" (
	"gpkg_uuid" UUID,
	"uppdrag_uuid" UUID,
	PRIMARY KEY("gpkg_uuid", "uppdrag_uuid")
);




CREATE TABLE IF NOT EXISTS "ages"."leverans" (
	"lev_uuid" UUID NOT NULL UNIQUE,
	"namn" TEXT,
	"organisation" INTEGER,
	"datum_lev" DATE,
	"datum_publ" DATE,
	PRIMARY KEY("lev_uuid")
);




CREATE TABLE IF NOT EXISTS "ages"."koordsys" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"sys_uri" TEXT,
	"name" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ages"."geodata_metadata" (
	"gpkg_uuid" UUID NOT NULL UNIQUE,
	"orginal_format" INTEGER,
	"org_koordsys" INTEGER,
	"nytt_koordsys" INTEGER,
	PRIMARY KEY("gpkg_uuid")
);


CREATE INDEX "ages"."geodata_metadata_index_0"
ON "geodata_metadata" ("gpkg_uuid");

CREATE TABLE IF NOT EXISTS "ages"."format" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ages"."swedigarch_uppdrag" (
	"swe_uuid" UUID NOT NULL UNIQUE,
	"gpkg_uuid" UUID NOT NULL,
	"de_data_vi_vill_ha" TEXT,
	PRIMARY KEY("swe_uuid", "gpkg_uuid")
);




CREATE TABLE IF NOT EXISTS "ages"."organisation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"org_uri" TEXT,
	"name" TEXT,
	PRIMARY KEY("id")
);



ALTER TABLE "ages"."geodata_info"
ADD FOREIGN KEY("gpkg_uuid") REFERENCES "geodata_metadata"("gpkg_uuid")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."rapportLank"
ADD FOREIGN KEY("gpkg_uuid") REFERENCES "ages"."geodata_info"("gpkg_uuid")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."rel2raa_arkiv"
ADD FOREIGN KEY("gpkg_uuid") REFERENCES "ages"."geodata_info"("gpkg_uuid")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."rel2uppdrag"
ADD FOREIGN KEY("gpkg_uuid") REFERENCES "geodata_info"("gpkg_uuid")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."geodata_info"
ADD FOREIGN KEY("leverans") REFERENCES "ages"."leverans"("lev_uuid")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."geodata_metadata"
ADD FOREIGN KEY("org_koordsys") REFERENCES "ages"."koordsys"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."geodata_metadata"
ADD FOREIGN KEY("nytt_koordsys") REFERENCES "koordsys"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "geodata_metadata"
ADD FOREIGN KEY("orginal_format") REFERENCES "ages"."format"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ages"."swedigarch_uppdrag"
ADD FOREIGN KEY("gpkg_uuid") REFERENCES "ages"."geodata_info"("gpkg_uuid")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ADD FOREIGN KEY("gpkg_uuid") REFERENCES "ages"."geodata_info"("gpkg_uuid")
ALTER TABLE "leverans"
ADD FOREIGN KEY("organisation") REFERENCES "ages"."organisation"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;